[package]
name = "lsr"
version = "0.1.0"
edition = "2024"

[dependencies]
chrono = "0.4"
clap = { version = "4", features = ["derive"] }
colored = "2"
tabular = { version = "0.2", features = ["ansi-cell"] }
terminal_size = "0.4"
uzers = "0.12"
uutils_term_grid = "0.6"
xattr = "1"
