[package]
name = "lsr"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = "0.4"
clap = { version = "4", features = ["derive"] }
colored = "2"
terminal_size = "0.3"
tabular = "0.2"
uzers = "0.12"
uutils_term_grid = "0.6"
