[package]
name = "lsr"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = "0.4"
clap = { version = "4", features = ["derive"] }
terminal_size = "0.3"
tabular = "0.2"
users = "0.11"
uutils_term_grid = "0.6"
