[package]
name = "ntalbs-lsr"
version = "0.1.0"
authors = ["ntalbs <ntalbsen@gmail.com>"]
edition = "2024"
description = "Very basic ls clone"
repository = "https://github.com/ntalbs/lsr"
license = "MIT"
keywords = ["ls", "cli"]
categories = ["command-line-utilities"]

[[bin]]
name = "lsr"
path = "src/main.rs"

[dependencies]
chrono = "0.4"
clap = { version = "4", features = ["derive"] }
colored = "3"
tabular = { version = "0.2", features = ["ansi-cell"] }
terminal_size = "0.4"
uzers = "0.12"
uutils_term_grid = "0.8"
xattr = "1"
